export const data = [
  {
    id: 1,
    zoom: 1,
    image: [["tiled/0/0/0.jpg"]],
  },
  {
    id: 2,
    zoom: 2,
    image: [
      ["tiled/1/0/0.jpg", "tiled/1/1/0.jpg"],
      ["tiled/1/0/1.jpg", "tiled/1/1/1.jpg"],
    ],
  },
  {
    id: 3,
    zoom: 3,
    image: [
      [
        "tiled/2/0/0.jpg",
        "tiled/2/1/0.jpg",
        "tiled/2/2/0.jpg",
        "tiled/2/3/0.jpg",
      ],
      [
        "tiled/2/0/1.jpg",
        "tiled/2/1/1.jpg",
        "tiled/2/2/1.jpg",
        "tiled/2/3/1.jpg",
      ],
      [
        "tiled/2/0/2.jpg",
        "tiled/2/1/2.jpg",
        "tiled/2/2/2.jpg",
        "tiled/2/3/2.jpg",
      ],
      [
        "tiled/2/0/3.jpg",
        "tiled/2/1/3.jpg",
        "tiled/2/2/3.jpg",
        "tiled/2/3/3.jpg",
      ],
    ],
  },
  {
    id: 4,
    zoom: 4,
    image: [
      [
        "tiled/3/0/0.jpg",
        "tiled/3/1/0.jpg",
        "tiled/3/2/0.jpg",
        "tiled/3/3/0.jpg",
        "tiled/3/4/0.jpg",
        "tiled/3/5/0.jpg",
        "tiled/3/6/0.jpg",
        "tiled/3/7/0.jpg",
      ],
      [
        "tiled/3/0/1.jpg",
        "tiled/3/1/1.jpg",
        "tiled/3/2/1.jpg",
        "tiled/3/3/1.jpg",
        "tiled/3/4/1.jpg",
        "tiled/3/5/1.jpg",
        "tiled/3/6/1.jpg",
        "tiled/3/7/1.jpg",
      ],
      [
        "tiled/3/0/2.jpg",
        "tiled/3/1/2.jpg",
        "tiled/3/2/2.jpg",
        "tiled/3/3/2.jpg",
        "tiled/3/4/2.jpg",
        "tiled/3/5/2.jpg",
        "tiled/3/6/2.jpg",
        "tiled/3/7/2.jpg",
      ],
      [
        "tiled/3/0/3.jpg",
        "tiled/3/1/3.jpg",
        "tiled/3/2/3.jpg",
        "tiled/3/3/3.jpg",
        "tiled/3/4/3.jpg",
        "tiled/3/5/3.jpg",
        "tiled/3/6/3.jpg",
        "tiled/3/7/3.jpg",
      ],
      [
        "tiled/3/0/4.jpg",
        "tiled/3/1/4.jpg",
        "tiled/3/2/4.jpg",
        "tiled/3/3/4.jpg",
        "tiled/3/4/4.jpg",
        "tiled/3/5/4.jpg",
        "tiled/3/6/4.jpg",
        "tiled/3/7/4.jpg",
      ],
      [
        "tiled/3/0/5.jpg",
        "tiled/3/1/5.jpg",
        "tiled/3/2/5.jpg",
        "tiled/3/3/5.jpg",
        "tiled/3/4/5.jpg",
        "tiled/3/5/5.jpg",
        "tiled/3/6/5.jpg",
        "tiled/3/7/5.jpg",
      ],
      [
        "tiled/3/0/6.jpg",
        "tiled/3/1/6.jpg",
        "tiled/3/2/6.jpg",
        "tiled/3/3/6.jpg",
        "tiled/3/4/6.jpg",
        "tiled/3/5/6.jpg",
        "tiled/3/6/6.jpg",
        "tiled/3/7/6.jpg",
      ],
      [
        "tiled/3/0/7.jpg",
        "tiled/3/1/7.jpg",
        "tiled/3/2/7.jpg",
        "tiled/3/3/7.jpg",
        "tiled/3/4/7.jpg",
        "tiled/3/5/7.jpg",
        "tiled/3/6/7.jpg",
        "tiled/3/7/7.jpg",
      ],
    ],
  },
];
